name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Berjalan setiap 12 jam
  workflow_dispatch: # Tombol manual

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Stats Images
        uses: xNok/github-stats-extended@v1.2.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }} # Menggunakan token rahasia
          user: RosyidStania
          theme: tokyonight # Menggunakan tema gelap
          hide_border: true
          bg_color: 0D1117

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/
          git commit -m "📊 Auto-update GitHub stats images" || exit 0
          git push
